//====Strip Function Names
//====([A-Za-z0-9_\*]+) +\(\*([A-Za-z0-9_]+)\)\(([A-Za-z0-9_ :\(\)\*\r\n,]*)\);
//====$2;
//====Strip Comments
//==== +// .*(\r?\n)
//====$1
//====Strip Extraneous Newlines
//====(\r?\n)(\r?\n)+
//====$1
//====Convert To HATCH Macros
//====^H +([A-Za-z0-9]*|)\.([A-Za-z0-9]+);
//====#define HATCH_$1$2 Engine::HatchFuncs.$1$2
//====^H +([A-Za-z0-9]+);
//====#define HATCH_$1 Engine::HatchFuncs.$1
//====Convert To SERVICE Macros
//====^S +([A-Za-z0-9]*|)\.([A-Za-z0-9]+);
//====#define SERVICE_$1$2 Engine::ServiceFuncs.$1$2
//====Cleanup
//====^(H|S).*\r?\n
//====
#define HATCH_AllocateGlobals Engine::HatchFuncs.AllocateGlobals
#define HATCH_EntityGet Engine::HatchFuncs.Entity.Get
#define HATCH_EntityGetIndex Engine::HatchFuncs.Entity.GetIndex
#define HATCH_EntityGetFromDrawGroup Engine::HatchFuncs.Entity.GetFromDrawGroup
#define HATCH_EntityGetIndexFromDrawGroup Engine::HatchFuncs.Entity.GetIndexFromDrawGroup
#define HATCH_EntityReset Engine::HatchFuncs.Entity.Reset
#define HATCH_EntityResetAtIndex Engine::HatchFuncs.Entity.ResetAtIndex
#define HATCH_EntityCreate Engine::HatchFuncs.Entity.Create
#define HATCH_EntityCopy Engine::HatchFuncs.Entity.Copy
#define HATCH_EntityMove Engine::HatchFuncs.Entity.Move
#define HATCH_EntityIsOnScreen Engine::HatchFuncs.Entity.IsOnScreen
#define HATCH_EntityIsPointOnScreen Engine::HatchFuncs.Entity.IsPointOnScreen
#define HATCH_ClassAdd Engine::HatchFuncs.Class.Add
#define HATCH_ClassCreateGlobalClass Engine::HatchFuncs.Class.CreateGlobalClass
#define HATCH_ClassSetupAttribute Engine::HatchFuncs.Class.SetupAttribute
#define HATCH_ClassLoadStaticObject Engine::HatchFuncs.Class.LoadStaticObject
#define HATCH_ClassSearchEntity Engine::HatchFuncs.Class.SearchEntity
#define HATCH_ClassSearchInteractableEntity Engine::HatchFuncs.Class.SearchInteractableEntity
#define HATCH_ClassEndSearch Engine::HatchFuncs.Class.EndSearch
#define HATCH_ClassGetEntityCount Engine::HatchFuncs.Class.GetEntityCount
#define HATCH_CollisionEntitiesAABB Engine::HatchFuncs.Collision.EntitiesAABB
#define HATCH_CollisionEntitiesCircular Engine::HatchFuncs.Collision.EntitiesCircular
#define HATCH_CollisionEntitiesSolid Engine::HatchFuncs.Collision.EntitiesSolid
#define HATCH_CollisionEntitiesPlatform Engine::HatchFuncs.Collision.EntitiesPlatform
#define HATCH_CollisionApplyTile360 Engine::HatchFuncs.Collision.ApplyTile360
#define HATCH_CollisionTileHit Engine::HatchFuncs.Collision.TileHit
#define HATCH_CollisionTileGrip Engine::HatchFuncs.Collision.TileGrip
#define HATCH_UpdateBoundsAdd Engine::HatchFuncs.UpdateBounds.Add
#define HATCH_UpdateBoundsClearAll Engine::HatchFuncs.UpdateBounds.ClearAll
#define HATCH_DrawSprite Engine::HatchFuncs.Draw.Sprite
#define HATCH_DrawSpritePart Engine::HatchFuncs.Draw.SpritePart
#define HATCH_DrawAnimation Engine::HatchFuncs.Draw.Animation
#define HATCH_DrawImage Engine::HatchFuncs.Draw.Image
#define HATCH_DrawImagePart Engine::HatchFuncs.Draw.ImagePart
#define HATCH_DrawTile Engine::HatchFuncs.Draw.Tile
#define HATCH_DrawCopyImageToTiles Engine::HatchFuncs.Draw.CopyImageToTiles
#define HATCH_DrawSetCompareColor Engine::HatchFuncs.Draw.SetCompareColor
#define HATCH_DrawSetPixelFilter Engine::HatchFuncs.Draw.SetPixelFilter
#define HATCH_DrawSetDrawToScreen Engine::HatchFuncs.Draw.SetDrawToScreen
#define HATCH_DrawLine Engine::HatchFuncs.Draw.Line
#define HATCH_DrawCircle Engine::HatchFuncs.Draw.Circle
#define HATCH_DrawCircleStroke Engine::HatchFuncs.Draw.CircleStroke
#define HATCH_DrawRing Engine::HatchFuncs.Draw.Ring
#define HATCH_DrawEllipse Engine::HatchFuncs.Draw.Ellipse
#define HATCH_DrawRectangle Engine::HatchFuncs.Draw.Rectangle
#define HATCH_DrawTriangle Engine::HatchFuncs.Draw.Triangle
#define HATCH_DrawPolygon Engine::HatchFuncs.Draw.Polygon
#define HATCH_DrawPolygonBlend Engine::HatchFuncs.Draw.PolygonBlend
#define HATCH_DrawFadeScreen Engine::HatchFuncs.Draw.FadeScreen
#define HATCH_AnimatorSet Engine::HatchFuncs.Animator.Set
#define HATCH_AnimatorSet3D Engine::HatchFuncs.Animator.Set3D
#define HATCH_AnimatorUpdate Engine::HatchFuncs.Animator.Update
#define HATCH_AnimatorGetHitbox Engine::HatchFuncs.Animator.GetHitbox
#define HATCH_AnimatorGetFrameID Engine::HatchFuncs.Animator.GetFrameID
#define HATCH_View3DSetAmbientLighting Engine::HatchFuncs.View3D.SetAmbientLighting
#define HATCH_View3DSetDiffuseLighting Engine::HatchFuncs.View3D.SetDiffuseLighting
#define HATCH_View3DSetSpecularLighting Engine::HatchFuncs.View3D.SetSpecularLighting
#define HATCH_View3DDrawBegin Engine::HatchFuncs.View3D.DrawBegin
#define HATCH_View3DDrawFinish Engine::HatchFuncs.View3D.DrawFinish
#define HATCH_View3DDrawModel Engine::HatchFuncs.View3D.DrawModel
#define HATCH_PaletteLoad Engine::HatchFuncs.Palette.Load
#define HATCH_PaletteGetColor Engine::HatchFuncs.Palette.GetColor
#define HATCH_PaletteSetColor Engine::HatchFuncs.Palette.SetColor
#define HATCH_PaletteMixPalettes Engine::HatchFuncs.Palette.MixPalettes
#define HATCH_PaletteRotateColorsLeft Engine::HatchFuncs.Palette.RotateColorsLeft
#define HATCH_PaletteRotateColorsRight Engine::HatchFuncs.Palette.RotateColorsRight
#define HATCH_PaletteCopyColors Engine::HatchFuncs.Palette.CopyColors
#define HATCH_PaletteSetPaletteIndexLines Engine::HatchFuncs.Palette.SetPaletteIndexLines
#define HATCH_DrawGroupAddEntity Engine::HatchFuncs.DrawGroup.AddEntity
#define HATCH_DrawGroupReorderEntities Engine::HatchFuncs.DrawGroup.ReorderEntities
#define HATCH_DrawGroupSetPrefixFunction Engine::HatchFuncs.DrawGroup.SetPrefixFunction
#define HATCH_DrawGroupSetSorting Engine::HatchFuncs.DrawGroup.SetSorting
#define HATCH_ViewSetSize Engine::HatchFuncs.View.SetSize
#define HATCH_ViewSetClip Engine::HatchFuncs.View.SetClip
#define HATCH_ViewResetClip Engine::HatchFuncs.View.ResetClip
#define HATCH_ResourcesLoadSprite Engine::HatchFuncs.Resources.LoadSprite
#define HATCH_ResourcesLoadImage Engine::HatchFuncs.Resources.LoadImage
#define HATCH_ResourcesLoadMesh Engine::HatchFuncs.Resources.LoadMesh
#define HATCH_ResourcesLoadView3D Engine::HatchFuncs.Resources.LoadView3D
#define HATCH_ResourcesLoadSound Engine::HatchFuncs.Resources.LoadSound
#define HATCH_LayerGetCount Engine::HatchFuncs.Layer.GetCount
#define HATCH_LayerGetLayerFromIndex Engine::HatchFuncs.Layer.GetLayerFromIndex
#define HATCH_LayerGetLayerFromName Engine::HatchFuncs.Layer.GetLayerFromName
#define HATCH_LayerGetIndexFromLayer Engine::HatchFuncs.Layer.GetIndexFromLayer
#define HATCH_LayerGetIndexFromName Engine::HatchFuncs.Layer.GetIndexFromName
#define HATCH_LayerGetTile Engine::HatchFuncs.Layer.GetTile
#define HATCH_LayerGetTileLine Engine::HatchFuncs.Layer.GetTileLine
#define HATCH_LayerGetSize Engine::HatchFuncs.Layer.GetSize
#define HATCH_TileConfigGetAngle Engine::HatchFuncs.TileConfig.GetAngle
#define HATCH_TileConfigSetAngle Engine::HatchFuncs.TileConfig.SetAngle
#define HATCH_TileConfigGetBehaviorFlag Engine::HatchFuncs.TileConfig.GetBehaviorFlag
#define HATCH_TileConfigSetBehaviorFlag Engine::HatchFuncs.TileConfig.SetBehaviorFlag
#define HATCH_SceneGotoNext Engine::HatchFuncs.Scene.GotoNext
#define HATCH_SceneSetNextFromCategory Engine::HatchFuncs.Scene.SetNextFromCategory
#define HATCH_SceneSetNext Engine::HatchFuncs.Scene.SetNext
#define HATCH_SceneGetName Engine::HatchFuncs.Scene.GetName
#define HATCH_StageMatchCurrentStageName Engine::HatchFuncs.Stage.MatchCurrentStageName
#define HATCH_StageGetCurrentStageName Engine::HatchFuncs.Stage.GetCurrentStageName
#define HATCH_MathSin256 Engine::HatchFuncs.Math.Sin256
#define HATCH_MathCos256 Engine::HatchFuncs.Math.Cos256
#define HATCH_MathTan256 Engine::HatchFuncs.Math.Tan256
#define HATCH_MathAsin256 Engine::HatchFuncs.Math.Asin256
#define HATCH_MathAcos256 Engine::HatchFuncs.Math.Acos256
#define HATCH_MathAtan256 Engine::HatchFuncs.Math.Atan256
#define HATCH_MathSin512 Engine::HatchFuncs.Math.Sin512
#define HATCH_MathCos512 Engine::HatchFuncs.Math.Cos512
#define HATCH_MathTan512 Engine::HatchFuncs.Math.Tan512
#define HATCH_MathAsin512 Engine::HatchFuncs.Math.Asin512
#define HATCH_MathAcos512 Engine::HatchFuncs.Math.Acos512
#define HATCH_MathSin1024 Engine::HatchFuncs.Math.Sin1024
#define HATCH_MathCos1024 Engine::HatchFuncs.Math.Cos1024
#define HATCH_MathTan1024 Engine::HatchFuncs.Math.Tan1024
#define HATCH_MathAsin1024 Engine::HatchFuncs.Math.Asin1024
#define HATCH_MathAcos1024 Engine::HatchFuncs.Math.Acos1024
#define HATCH_MathSqrt Engine::HatchFuncs.Math.Sqrt
#define HATCH_MathDistance Engine::HatchFuncs.Math.Distance
#define HATCH_MathAbs Engine::HatchFuncs.Math.Abs
#define HATCH_MathMin Engine::HatchFuncs.Math.Min
#define HATCH_MathMax Engine::HatchFuncs.Math.Max
#define HATCH_MathClamp Engine::HatchFuncs.Math.Clamp
#define HATCH_MathGetRandom Engine::HatchFuncs.Math.GetRandom
#define HATCH_MathSetRandomSeed Engine::HatchFuncs.Math.SetRandomSeed
#define HATCH_MathGetRandomSeeded Engine::HatchFuncs.Math.GetRandomSeeded
#define HATCH_MatrixIdentity Engine::HatchFuncs.Matrix.Identity
#define HATCH_MatrixMultiply Engine::HatchFuncs.Matrix.Multiply
#define HATCH_MatrixTranslate Engine::HatchFuncs.Matrix.Translate
#define HATCH_MatrixIdentityScale Engine::HatchFuncs.Matrix.IdentityScale
#define HATCH_MatrixIdentityRotationX Engine::HatchFuncs.Matrix.IdentityRotationX
#define HATCH_MatrixIdentityRotationY Engine::HatchFuncs.Matrix.IdentityRotationY
#define HATCH_MatrixIdentityRotationZ Engine::HatchFuncs.Matrix.IdentityRotationZ
#define HATCH_MatrixIdentityRotationXYZ Engine::HatchFuncs.Matrix.IdentityRotationXYZ
#define HATCH_AudioPlayStream Engine::HatchFuncs.Audio.PlayStream
#define HATCH_AudioPlaySoundFX Engine::HatchFuncs.Audio.PlaySoundFX
#define HATCH_AudioStopSoundFX Engine::HatchFuncs.Audio.StopSoundFX
#define HATCH_AudioIsSoundFXPlaying Engine::HatchFuncs.Audio.IsSoundFXPlaying
#define HATCH_AudioPlaybackAlter Engine::HatchFuncs.Audio.PlaybackAlter
#define HATCH_AudioPlaybackIsValid Engine::HatchFuncs.Audio.PlaybackIsValid
#define HATCH_AudioPlaybackGetSamplePosition Engine::HatchFuncs.Audio.PlaybackGetSamplePosition
#define HATCH_AudioPlaybackStop Engine::HatchFuncs.Audio.PlaybackStop
#define HATCH_AudioPlaybackPause Engine::HatchFuncs.Audio.PlaybackPause
#define HATCH_AudioPlaybackResume Engine::HatchFuncs.Audio.PlaybackResume
#define HATCH_AudioPlaybackPauseAll Engine::HatchFuncs.Audio.PlaybackPauseAll
#define HATCH_AudioPlaybackResumeAll Engine::HatchFuncs.Audio.PlaybackResumeAll
#define HATCH_TouchGetX Engine::HatchFuncs.Touch.GetX
#define HATCH_TouchGetY Engine::HatchFuncs.Touch.GetY
#define HATCH_TouchIsDown Engine::HatchFuncs.Touch.IsDown
#define HATCH_TouchIsPressed Engine::HatchFuncs.Touch.IsPressed
#define HATCH_TouchIsReleased Engine::HatchFuncs.Touch.IsReleased
#define HATCH_StringInit Engine::HatchFuncs.String.Init
#define HATCH_StringFromUnicode Engine::HatchFuncs.String.FromUnicode
#define HATCH_StringFromCString Engine::HatchFuncs.String.FromCString
#define HATCH_StringFromResource Engine::HatchFuncs.String.FromResource
#define HATCH_StringCopy Engine::HatchFuncs.String.Copy
#define HATCH_StringConcat Engine::HatchFuncs.String.Concat
#define HATCH_StringRealloc Engine::HatchFuncs.String.Realloc
#define HATCH_StringMatch Engine::HatchFuncs.String.Match
#define HATCH_StringToCString Engine::HatchFuncs.String.ToCString
#define HATCH_SocketCreate Engine::HatchFuncs.Socket.Create
#define HATCH_SocketClose Engine::HatchFuncs.Socket.Close
#define HATCH_SocketConnect Engine::HatchFuncs.Socket.Connect
#define HATCH_SocketBind Engine::HatchFuncs.Socket.Bind
#define HATCH_SocketListen Engine::HatchFuncs.Socket.Listen
#define HATCH_SocketAccept Engine::HatchFuncs.Socket.Accept
#define HATCH_SocketRead Engine::HatchFuncs.Socket.Read
#define HATCH_SocketWrite Engine::HatchFuncs.Socket.Write
#define SERVICE_CoreGetLocale Engine::ServiceFuncs.Core.GetLocale
#define SERVICE_CoreGetConfirmButtonFlip Engine::ServiceFuncs.Core.GetConfirmButtonFlip
#define SERVICE_CoreIsMobile Engine::ServiceFuncs.Core.IsMobile
#define SERVICE_CoreCanExitGame Engine::ServiceFuncs.Core.CanExitGame
#define SERVICE_CoreExitGame Engine::ServiceFuncs.Core.ExitGame
#define SERVICE_CoreLaunchManual Engine::ServiceFuncs.Core.LaunchManual
#define SERVICE_CoreGetSafeViewMargins Engine::ServiceFuncs.Core.GetSafeViewMargins
#define SERVICE_CoreShowInputDeviceConfigOverlay Engine::ServiceFuncs.Core.ShowInputDeviceConfigOverlay
#define SERVICE_CoreIsEntitlementEnabled Engine::ServiceFuncs.Core.IsEntitlementEnabled
#define SERVICE_CoreShowEntitlementOverlay Engine::ServiceFuncs.Core.ShowEntitlementOverlay
#define SERVICE_UserDataShowUserProfileOverlay Engine::ServiceFuncs.UserData.ShowUserProfileOverlay
#define SERVICE_UserDataUnlockAchievement Engine::ServiceFuncs.UserData.UnlockAchievement
#define SERVICE_UserDataGetAchievementsEnabled Engine::ServiceFuncs.UserData.GetAchievementsEnabled
#define SERVICE_UserDataSetAchievementsEnabled Engine::ServiceFuncs.UserData.SetAchievementsEnabled
#define SERVICE_UserDataUpdateRichPresence Engine::ServiceFuncs.UserData.UpdateRichPresence
#define SERVICE_UserDataClearRichPresence Engine::ServiceFuncs.UserData.ClearRichPresence
#define SERVICE_UserStorageTryInitStorage Engine::ServiceFuncs.UserStorage.TryInitStorage
#define SERVICE_UserStorageGetStorageStatus Engine::ServiceFuncs.UserStorage.GetStorageStatus
#define SERVICE_UserStorageGetStoragePermission Engine::ServiceFuncs.UserStorage.GetStoragePermission
#define SERVICE_UserStorageStoragePermissionReset Engine::ServiceFuncs.UserStorage.StoragePermissionReset
#define SERVICE_UserStorageStoragePermissionRequestBegin Engine::ServiceFuncs.UserStorage.StoragePermissionRequestBegin
#define SERVICE_UserStorageStoragePermissionRequestGrant Engine::ServiceFuncs.UserStorage.StoragePermissionRequestGrant
#define SERVICE_UserStorageStoragePermissionRequestDeny Engine::ServiceFuncs.UserStorage.StoragePermissionRequestDeny
#define SERVICE_UserStorageStoragePermissionRequestErrorOut Engine::ServiceFuncs.UserStorage.StoragePermissionRequestErrorOut
#define SERVICE_UserStorageNoSaveModeEnable Engine::ServiceFuncs.UserStorage.NoSaveModeEnable
#define SERVICE_UserStorageIsNoSaveModeEnabled Engine::ServiceFuncs.UserStorage.IsNoSaveModeEnabled
#define SERVICE_UserStorageReadSaveFile Engine::ServiceFuncs.UserStorage.ReadSaveFile
#define SERVICE_UserStorageWriteSaveFile Engine::ServiceFuncs.UserStorage.WriteSaveFile
#define SERVICE_UserStorageDeleteSaveFile Engine::ServiceFuncs.UserStorage.DeleteSaveFile
#define SERVICE_WifiP2PIsSupported Engine::ServiceFuncs.WifiP2P.IsSupported
#define SERVICE_WifiP2PInit Engine::ServiceFuncs.WifiP2P.Init
#define SERVICE_WifiP2PDiscoverPeers Engine::ServiceFuncs.WifiP2P.DiscoverPeers
#define SERVICE_WifiP2PRequestPeers Engine::ServiceFuncs.WifiP2P.RequestPeers
#define SERVICE_WifiP2PConnectToPeer Engine::ServiceFuncs.WifiP2P.ConnectToPeer
