#define FRAMEBUFFER_WIDTH 424
#define FRAMEBUFFER_HEIGHT 240
#define MAX_FRAMEBUFFER_WIDTH 512
#define MAX_FRAMEBUFFER_HEIGHT 256
#define MAX_PALETTE_COUNT 8
#define MAX_DEFORM_LINES 0x400
#define MAX_VIEWPORTS 8
#define MAX_LAYERS 64
#define MAX_DRAWGROUPS 16
#define MAX_SLOT_ENTITIES 0x800
#define MAX_SPAWN_ENTITIES 0x100
#define MAX_RESERVED_ENTITIES 0x40
#define MAX_ENTITIES (MAX_SLOT_ENTITIES + MAX_SPAWN_ENTITIES + MAX_RESERVED_ENTITIES)
#define TILE_SIZE 0x10
#define TILE_SIZE_MASK 0xF
#define TILE_SIZE_IN_BITS 4
#define MAX_TILE_COUNT 0x1000
#define MAX_CLASSES 0x100
#define MAX_CLASS_SLOTLISTS (MAX_CLASSES + 4)
#define MAX_IMAGES 1024
#define MAX_SPRITES 256
#define MAX_SOUNDS 256
#define MAX_MESHES 64
#define MAX_AUDIO_STREAMS 2
#define MAX_AUDIO_PLAYBACKS 16
#define MAX_ARRAY_BUFFERS 4
#define MAX_RESOURCE_PACKS 8

#define TILE_COLLA_MASK 0x0000C000U
#define TILE_COLLB_MASK 0x00030000U
#define TILE_FLIPX_MASK 0x00001000U
#define TILE_FLIPY_MASK 0x00002000U
#define TILE_IDENT_MASK 0x00000FFFU
#define TILE_FXYID_MASK 0x00003FFFU
#define TILE_EMPTY      0xFFFFFFFFU

#define RESOURCE_PREFIX "Resources/"

#if MAX_ENTITIES >= 0x10000
#error "Value of MAX_ENTITIES outside of allowed range"
#endif
